//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRHm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaEMpleados
    {
        public int Id { get; set; }
        public string Empleado { get; set; }
        public string TipoSalida { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaSalida { get; set; }
    }
}
